apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: <%= serviceName %>

build:
  artifacts:
    - image: <%= serviceName %>
      context: .
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "app/**/*.py"
            dest: "/app"

deploy:
  helm:
    releases:
      - name: dev-<%= serviceName %>
        chartPath: ./helm
        createNamespace: true
        setValues:
          image.repository: <%= serviceName %>
          # Ensure image.tag is set by Skaffold's build output
        setValueTemplates:
          image.tag: "{{.IMAGE_TAG}}"
        namespace: scholar-spark-dev
        upgradeOnChange: true

portForward:
  - resourceType: service
    resourceName: dev-<%= serviceName %>
    namespace: scholar-spark-dev
    port: <%= port %>
    localPort: <%= port %>
