# Default values for <%= serviceName %>.
replicaCount: 1

image:
  repository: <%= serviceName %>
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

# Add serviceAccount configuration
serviceAccount:
  create: false # Use the default service account
  # annotations: {}
  # name: ""

service:
  type: ClusterIP
  port: <%= port %>

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

# Add probe configurations
# Health Checks - Adjusted timings
livenessProbe:
  httpGet:
    path: /health
    port: http # Use named port
  initialDelaySeconds: 60 # Increased delay
  periodSeconds: 15
  timeoutSeconds: 5  # Increased timeout
  failureThreshold: 5 # Increased threshold

readinessProbe:
  httpGet:
    path: /health
    port: http # Use named port
  initialDelaySeconds: 30 # Increased delay
  periodSeconds: 10
  timeoutSeconds: 5  # Increased timeout
  failureThreshold: 5 # Increased threshold

env: {}

development:
  enabled: true
  volumes:
    - name: app-code
      hostPath:
        path: ./app
        type: Directory
  volumeMounts:
    - name: app-code
      mountPath: /app/app
      readOnly: true
